"""Add column data hora refeição tabela dieta

Revision ID: 35d903f5bf94
Revises: 
Create Date: 2024-10-20 06:37:13.599410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d903f5bf94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dieta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora_refeicao', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dieta', schema=None) as batch_op:
        batch_op.drop_column('data_hora_refeicao')

    # ### end Alembic commands ###
